apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node
  name: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
       app: node

  template:
    metadata:
      labels:
         app: node
    spec:
      containers:
      - image: farhanluckali/node-helloworld:2022-05-28--29-56
        name: node
