apiVersion: v1
kind: Service
metadata:
  name: my-app1
  annotations:
  labels:
    app: node
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 4001
    targetPort: 4001
  selector:
    app: node
